# Site settings
title: Nick Walsh
description: "Nick Walsh's personal site"
#baseurl: "/jekyll-personal-site" # for test: remove string '/space-jekyll-template' to ''
baseurl: ''
#url: "http://nmwalsh.github.io/jekyll-personal-site/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
url: ''

# User settings
username: Nick Walsh
user_title: Developer Evangelist, @Datmo
email: nicholaswalsh.official@gmail.com
twitter_username: thenickwalsh
github_username:  nmwalsh
medium_username: nicholasmwalsh
profile_picture: /assets/img/tomcruise.png
linkedin_public_url: thenickwalsh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: about me
      url: /about
      key_trigger: 2
    - title: blog (coming soon)
      url: ""
      key_trigger: 3
    - title: talks (coming soon)
      url: ""
      key_trigger: 4
    - title: events (coming soon)
      url: ""
      key_trigger: 5
    #- title: resume
    #  url: /resume
    #  key_trigger: r
    #- title: series
    #  url: /series
    #  key_trigger: 3
    #- title: tags
    #  url: /tags
    #  key_trigger: 4

  section_2:
    - title: github
      url: https://www.github.com/nmwalsh
      new_tab: true
      key_trigger: g
    - title: twitter
      url: https://www.twitter.com/thenickwalsh
      key_trigger: t
    - title: medium
      url: https://www.medium.com/@nicholasmwalsh
      key_trigger: m
    - title: linkedin
      url: https://www.linkedin.com/thenickwalsh
      key_trigger: l
    - title: slides
      url: https://www.slides.com/walsh
      key_trigger: w

  section_3:
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s", as defined in zmain.js
    - title: quit
      url: ""
      key_trigger: q #WARNING: search only works with "s"
    

# projects in header index
projects:
  - name: ğŸŒƒ style-twitter-bot
    url: https://github.com/nmwalsh/style-twitter-bot
  - name: ğŸ¦… datmo_falcon_api
    url: https://github.com/nmwalsh/datmo_falcon_api
  - name: ğŸ’¸ authorizenet-payments-boilerplate
    url: https://github.com/nmwalsh/authorizenet-python-demo
  - name: â­ Datmo website redesign
    url: https://datmo.com/

talks:
  - name: ğŸ¤– Building Apps with Machine Learning
    url: http://slides.com/walsh/appswithai
  - name: ğŸ““ Version Control for Machine Learning and AI
    url: https://slides.com/walsh/ai-version-control
  - name: ğŸ“¦ The Need for Standardized MLOps
    url: https://slides.com/walsh/standards-in-ml-ops
  - name: ğŸ“º The Story of Twitch
    url: https://slides.com/walsh/story-of-twitch
  - name: ğŸ“Š Intro to TensorFlow + Machine Learning Version Control
    url: https://slides.com/walsh/intro-to-tf-and-ml-version-control

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
